I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 544, in script
    t "Link loader operating at 98% efficiency. Cargo processing resumed."
TypeError: must be real number, not TagQuotingDict

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 544, in script
    t "Link loader operating at 98% efficiency. Cargo processing resumed."
  File "/Users/norrisa/Documents/dev/github/linkloadervn/current/renpy-8.3.7-sdk/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/Users/norrisa/Documents/dev/github/linkloadervn/current/renpy-8.3.7-sdk/renpy/ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Users/norrisa/Documents/dev/github/linkloadervn/current/renpy-8.3.7-sdk/renpy/exports/sayexports.py", line 121, in say
    what = what % tag_quoting_dict
TypeError: must be real number, not TagQuotingDict

macOS-15.4.1-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
terminal.cowboy 0.1.2
Fri May  9 21:28:46 2025
